// Listado maestro de corredores y equipos ciclistas (Tour de Francia 2026)
// Se usa solo para autocompletar en el panel de admin. No afecta a la puntuación.

const CORREDORES_MAESTRO = [
"A PARET PEINTRE","ABRAHAMSEN","ACKERMANN","AFFINI","ALAPHILIPPE","ALEX MOLENAAR","ALLEGAERT",
"ANDERS JOHANNESSEN","ARANBURU","ARENSMAN","ARMIRAIL","ARTZ","ASKEY","AYUSO","AZPARREN",
"BALDERSTONE","BALLERINI","BARGUIL","BAUDIN","BAUHAUS","BEN HEALY","BEN THOMAS","BENOOT",
"BERCKMOES","BERNAL","BERWICK","BIERMANS","BIESTERBOS","BITTNER","BRAZ AFONSO","BREUILLARD",
"C BERTHET","CAMPENAERTS","CARAPAZ","CARUSO","CASTRILLO","CATTANEO","CEES BOL","CEPEDA",
"CHARMIG","CHRIS HARPER","CORT NIELSEN","COSTIOU","CRAPS","DE KLEIJN","DE LIE","DEBRUYNE",
"DEGENKOLB","DEL TORO","DELBOVE","DELETTRE","DENZ","DEREK GEE","DHONDT","DILLIER",
"DORIAN GODON","DURBRIDGE","EENKHOORN","ENGELHARDT","EVENEPOEL","FRED WRIGHT","FRETIN","FRIGO",
"G BENNET","G MARTIN","GANNA","GATE","GAVIRIA","GERMANI","GIRMAY","GRADEK","GROSSCHARTNER",
"GUERNALEC","HERMANS","HESSMANN","HIGUITA","HINDLEY","HOOLE","HOWSON","HUGO PAGE","IZAGUIRRE",
"J F PARRA","JAVIER ROMO","JOEL NICOLAU","JORDAN JEGAT","JORGENSON","K ASGREEN","KIRSCH","KOOIJ",
"KUSS","KWIATKOWSKI","LE BERRE","LENNY MTNZ","LIPOWITZ","LOUVEL","LUKE PLAPP","MARC HIRSCHI",
"MARCO HALLER","MARKL","MARSMAN","MATTHEWS","MAX KANTER","MC NULTY","MERLIER","MEURISSE",
"MOHORIC","NEILANDS","O BRIEN","O CONNOR","OLDANI","OLIVEIRA","OTRUBA","PACHER","PEDERSEN",
"PER STRAND HAGENES","PHILIPSEN","PIGANZOLI","PLANCKAERT","PLUIMERS","POGACAR","POLITT",
"PRODHOMME","R GREGOIRE","RAÚL G PIERNA","RICCITELLO","RICKAERT","RUBIO","RUSSO","SCHMID",
"SEAN QUINN","SEIXAS","SIMMONS","SKAARSETH","SKJELMOSE","SKUJINS","SLOCK","STANNARD",
"STEINHAUSER","STEWART","STORER","STUYVEN","TARLING","TEJADA","TEUNISSEN","TIBERI","TOBIAS FOSS",
"TOBIAS JOHANNESSEN","TOM PIDCOCK","TRAEEN","TRATNIK","TRENTIN","TURGIS","UIJTDEBROEKS",
"V PARET PEINTRE","VACEK","VALGREN","VAN ASBROECK","VAN BAARLE","VAN DEN BERG","VAN DEN BROEK",
"VAN DER POEL","VAN DIJKE","VAN EETVELT","VAN GILS","VAN MOER","VAN WILDER","VAUQUELIN",
"VEISTROFFER","VELASCO","VEN LERBERGHE","VEN MECHELEN","VERCHER","VERMEERSCH","VERONA",
"VERSTRYNGE","VERVAEKE","VINGEGAARD","VINOKUROV","WAERENSKJOLD","WALKER","WELLENS",
"YANNIS VOISARD","YATES","ZIMMERMANN"
];

const EQUIPOS_MAESTRO = [
"UAE","ALPECIN","BAHRAIN","DECATHLON","EF","FDJ","INEOS","LIDL-TREK","LOTTO","MOVISTAR",
"NSN","RED BULL","SOUDAL QUICK STEP","JAYCO ALULA","PICNIC","VISMA","UNO-X","XDS ASTANA",
"COFIDIS","TUDOR","TOTAL ENERGIES","CAJA RURAL","PINARELLO"
];
